name: "Dockerfile-Linting"

on:
  pull_request:
    branches: 
    - master
    paths:
    - ./services/distribution/Dockerfile
    - ./services/submission/Dockerfile

jobs:
  distribution:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Pull HaDoLint image
      run: docker pull hadolint/hadolint
    - name: Lint Dockerfile
      run: docker run --rm --interactive hadolint/hadolint < ./services/distribution/Dockerfile
  submission:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Pull HaDoLint image
      run: docker pull hadolint/hadolint
    - name: Lint Dockerfile
      run: docker run --rm --interactive hadolint/hadolint < ./services/submission/Dockerfile

